# Generated by Django 5.0.6 on 2024-06-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='presidente',
        ),
    ]
