# Generated by Django 5.0.6 on 2024-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futapp', '0002_remove_equipo_presidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mes',
            field=models.CharField(blank=True, choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, null=True),
        ),
    ]
